version: 0.0
os: linux
files:
  - source: /
    destination: /nodeapp

permissions:
- object: /
  pattern: "**"
  owner: ubuntu
  group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/npm-start.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/stop-server.sh
      timeout: 300
      runas: root
