version: 0.2

phases:
  install:
    commands:
      # install node 13
      - echo Installing Node 13...
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt-get install -y nodejs

    pre_build:
      commands:
        # install dependencies
        - echo Installing dependencies...
        - npm install

    build:
      commands:
        # test
        # build
        - echo Building with NPM
        - npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist

